CREATE TABLE IF NOT EXISTS EVENTS(
  ID UUID PRIMARY KEY,
  EXTERNAL_ID VARCHAR(64) NOT NULL,
  ORIGIN VARCHAR(16) NOT NULL,
  TITLE VARCHAR(32) NOT NULL,
  DESCRIPTION VARCHAR(1024) NOT NULL,
  POSTER VARCHAR(255) NOT NULL,
  EVENT_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  MAX_TICKETS INTEGER NOT NULL,
  SOLD_TICKETS INTEGER NOT NULL DEFAULT 0,
  UNIQUE (EXTERNAL_ID, ORIGIN)
)
